name = "DSLean"
version = "0.1.0"
defaultTargets = ["dslean"]

[[lean_lib]]
name = "DSLean"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.27.0"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0"

[[require]]
name = "Cli"
scope = "leanprover"
rev = "v4.27.0"

[[lean_exe]]
name = "dslean"
root = "Main"
